### ISSUE TITLE
[PROG] Linear Search

### ISSUE THREAD

**Issue by unshDee** [GDSC-AUM/OpenOcto-DSA#11]
**Program Description**
Program to implement Linear Search.

**Additional**
Update the documentation (`DOC.md` in `searching` folder) to include linear search.

**Checklist**
- [x] This issue has not been mentioned in existing issues.

**Comment by unshDee** [comment]
Sure!
Assigning it to you.

**Comment by Rohit-8** [comment]
Please assign this issue to me. I can solve this problem.

**Comment by virajshitole** [comment]
i want to work on this issue. can you assign this issue to me?

**Comment by anuragnewbie** [comment]
Hello @Rohit-8 sir ! Sir, I am participating in hacktoberfest2021 and I want to make a contribution to this isue. Can you please assign this to me sir?

**Comment by anuragnewbie** [comment]
Hello @unshDee sir ! Sir, I am participating in hacktoberfest2021 and I want to make a contribution to this issue. Can you please assign this to me sir?

**Comment by unshDee** [comment]
Hello @virajshitole and @anuragnewbie, 
This issue has already been assigned to @Rohit-8.
I recommend you create issues and I'll assign those to you.

**Comment by anuragnewbie** [comment]
> Hello @virajshitole and @anuragnewbie, This issue has already been assigned to @Rohit-8. I recommend you create issues and I'll assign those to you.
okay @unshDee sir.

**Comment by anuragnewbie** [comment]
> Hello @virajshitole and @anuragnewbie, This issue has already been assigned to @Rohit-8. I recommend you create issues and I'll assign those to you.

hello @unshDee  sir ! Sir I have created a new issue sir...please have a look once sir.

**Comment by anuragnewbie** [comment]
hello @unshDee sir ! Sir I have created a new issue sir...please have a look once sir

**Comment by ayushanand09** [comment]
Hi @unshDee ,

Can you please assign this to me?
I will create a pull request for the above program as soon as you assign this to me.

**Comment by ayushanand09** [comment]
Hi @unshDee ,

I have added the program for **"linear search"**. Please check the recent pull request (#65)

In case of any difficulty, feel free to reach out.

Thanks,
Ayush
