### ISSUE TITLE
[PROG] Prim's Algorithm

### ISSUE THREAD

**Issue by unshDee** [GDSC-AUM/OpenOcto-DSA#20]
**Program Description**
Program to implement Prim's Algorithm.

**Additional**
Update the documentation (`DOC.md` in `greedy` folder) to include Prim's Algorithm.

**Checklist**
- [x] This issue has not been mentioned in existing issues.

**Comment by unshDee** [comment]
Yeah!

**Comment by ajay-makvana** [comment]
I want to work on this issue @unshDee assign it to me

**Comment by unshDee** [comment]
Hello @ajay-makvana, this issue has already been assigned to someone.
All the issues have been assigned so I recommend you create a new issue and I'll assign it to you.

**Comment by unshDee** [comment]
@ajay-makvana would you still like to work on this issue? There hasn't been any PRs for Prim's from the assignee.

**Comment by ajay-makvana** [comment]
> @ajay-makvana would you still like to work on this issue? There hasn't been any PRs for Prim's from the assignee.

this was not assigned to me ...

**Comment by unshDee** [comment]
> > @ajay-makvana would you still like to work on this issue? There hasn't been any PRs for Prim's from the assignee.
> 
> this was not assigned to me ...

I you want to; I can assign it to you🤔

**Comment by ajay-makvana** [comment]
> > > @ajay-makvana would you still like to work on this issue? There hasn't been any PRs for Prim's from the assignee.
> > 
> > 
> > this was not assigned to me ...
> 
> I you want to; I can assign it to you🤔

Yes assign it too me i will solve it

**Comment by unshDee** [comment]
Done
