### ISSUE TITLE
[PROG] Prime Factors

### ISSUE THREAD

**Issue by unshDee** [GDSC-AUM/OpenOcto-DSA#23]
**Program Description**
Program to display prime factors of a number

**Additional context**
Update documentation (`DOC.md` in `mathematics` folder).

**Checklist**
- [x] This issue has not been mentioned in existing issues.

**Comment by nabeel001** [comment]
I would like to work on this issue.
pls assign this to me.

**Comment by ravi-varma-ankam** [comment]
Can I work on this Issue??

**Comment by nabeel001** [comment]
> > I would like to work on this issue. pls assign this to me.
> 
> Hey @nabeel001, you've already contributed twice, so I think it would be better to assign this to others who are contributing for the first time.... However, if you still want to contribute, just create an issue yourself and I'll assign it to you. Thanks for understanding!

Hey, You are right. I had same thoughts too and that's why I didn't take up this issue and send any pull request.

**Comment by unshDee** [comment]
> > > I would like to work on this issue. pls assign this to me.
> > 
> > 
> > Hey @nabeel001, you've already contributed twice, so I think it would be better to assign this to others who are contributing for the first time.... However, if you still want to contribute, just create an issue yourself and I'll assign it to you. Thanks for understanding!
> 
> Hey, You are right. I had same thoughts too and that's why I didn't take up this issue and send any pull request.

Thanks for understanding!
