### ISSUE TITLE
[PROG] Caesar Cipher 

### ISSUE THREAD

**Issue by bhantsi** [GDSC-AUM/OpenOcto-DSA#26]
**Program Description**
This program uses Caesar Cipher Algorithm to encrypt/decrypt plain text. It is a type of substitution cipher in which each letter in the plaintext is replaced by a letter with a fixed number of positions down the alphabet. 

**Additional context**
**INPUT:**
line 1: key (key)
line 2: message (s)

**OUTPUT:**
line 1: Encrypted message (t)

**Checklist**
- [x] This issue has not been mentioned in existing issues.

**Comment by unshDee** [comment]
Sure
