### ISSUE TITLE
[PROG] Binary Search C++ Program

### ISSUE THREAD

**Issue by anuragnewbie** [GDSC-AUM/OpenOcto-DSA#39]
**Program Description**
Hi @unshDee  sir! I want to add a binary search program implemented using c++ language to your repository.

**Additional context**
I will be using recursion here.

**Checklist**
- [ ] This issue has not been mentioned in existing issues.

**Comment by anuragnewbie** [comment]
Hi @unshDee  sir please assign this to me sir...

**Comment by unshDee** [comment]
Sorry @anuragnewbie this repository only accepts C++ programs!

**Comment by anuragnewbie** [comment]
> Sorry @anuragnewbie this repository only accepts C++ programs!

Sir, I can do it in c++ also if you permit me.

**Comment by unshDee** [comment]
Hey @anuragnewbie 
This issue was already created and the PR for it has already been merged around 11 hours ago.
I'd  suggest you create some other issue which has not been added yet

**Comment by anuragnewbie** [comment]
> Hey @anuragnewbie This issue was already created and the PR for it has already been merged around 11 hours ago. I'd suggest you create some other issue which has not been added yet

It's okay @unshDee ...I am backing off... thanx for ur help.
