### ISSUE TITLE
[PROG] Longest Common Subsequence

### ISSUE THREAD

**Issue by ajay-makvana** [GDSC-AUM/OpenOcto-DSA#40]
**Program Description**
Longest Common Subsequence

**Additional context**
Longest Common Subsequence Solution In Recursive + DP both
**Checklist**
- [ ] This issue has not been mentioned in existing issues.

**Comment by ajay-makvana** [comment]
I want to work on this issue assign it to me

**Comment by unshDee** [comment]
Assigned.
