### ISSUE TITLE
[PROG] Sliding Window Maximum

### ISSUE THREAD

**Issue by harshita9621** [GDSC-AUM/OpenOcto-DSA#66]
**Program Description**
You are given an array of integers nums, there is a sliding window of size k which is moving from the very left of the array to the very right. You can only see the k numbers in the window. Each time the sliding window moves right by one position.

Return the max sliding window.

**Additional context**
Input: nums = [1,3,-1,-3,5,3,6,7], k = 3
Output: [3,3,5,5,6,7]

**Checklist**
- [x] This issue has not been mentioned in existing issues.

**Comment by harshita9621** [comment]
@unshDee Can I  contribute on this issue

**Comment by unshDee** [comment]
Sure

**Comment by harshita9621** [comment]
@unshDee The PR is showing mature in 14 days ?
