### ISSUE TITLE
[PROG] Prime Number

### ISSUE THREAD

**Issue by unshDee** [GDSC-AUM/OpenOcto-DSA#7]
**Program Description**
Program to check whether a number is a prime number.

**Additional**
Update the documentation (`DOC.md` in `mathematics` folder) to include prime number program.

**Checklist**
- [x] This issue has not been mentioned in existing issues.

**Comment by Prontent11** [comment]
I would love to work on this issue.
If you could assign me this issue.
it would be greatly appreciated

**Comment by unshDee** [comment]
@khushibansal26 would you still like to take up this issue? I'll make you an assignee too just in case...

**Comment by khushibansal26** [comment]
Yes

**Comment by khushibansal26** [comment]
@unshDee Can you pls tell me how to do the submission? 
I am new to open source

**Comment by khushibansal26** [comment]
I have submitted it.Please check @unshDee

**Comment by khushibansal26** [comment]
Now check @unshDee I have done it  according to the guidelines

**Comment by unshDee** [comment]
> Now check @unshDee I have done it according to the guidelines

@khushibansal26 your PR is not showing any changes you made. [Your PR files](https://github.com/GDSC-AUM/OpenOcto-DSA/pull/55/files)
Also, sorry I didn't see your comment earlier😅
Regarding you being new to open source, there are plenty of sources that could help you learn about open source.
From tutorials on YouTube to videogames, the list is endless.

Regard your specific issue about updating your existing PR with the changes you made in your forked repo. [Check here on StackOverflow](https://stackoverflow.com/questions/9790448/how-to-update-a-pull-request-from-forked-repo).

Coming to learning about Git:
- [Here's a link from GitHub themselves](https://docs.github.com/en/get-started/quickstart/git-and-github-learning-resources)
- [Git Cheat Sheets from GitHub](https://training.github.com/)

I tried the game [Oh My Git!](https://ohmygit.org/) and learnt the basics of Git

**Comment by bhantsi** [comment]
Is this issue still available? I will like to work on it

**Comment by unshDee** [comment]
> Is this issue still available? I will like to work on it

Yes, the PR which was created by the previous assignee has not been updated, so I'll make you an assignee too.

**Comment by bhantsi** [comment]
Hey @unshDee check PR #64
